name: sqlite3_library_linux
description: Flutter package to bundle sqlite3 library to your linux apps
version: 2.1.0
repository: https://github.com/Milvintsiss/sqlite3_library_linux
homepage: https://github.com/Milvintsiss/sqlite3_library_linux
issue_tracker: https://github.com/Milvintsiss/sqlite3_library_windows/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - default_libsqlite3.so
    - old_libsqlite3.so